module.exports = {
    port: 3000,
    USE_HTTPS: false,
    TOKEN_SECRET: "Your Token",
    QRCODE_GENERATION_URL: "QRCODE_GENERATION_URL",
    QRCODE_VERIFY_URL: "QRCODE_VERIFY_URL",
    SENDGRID_API_KEY: "SENDGRID_API_KEY",
    SENDER_EMAIL: "SENDER_EMAIL"
};
